name: learn-github-actions
run-name: ${{ github.actor }} is learning GitHub Actions
on: [push]
jobs:
  tests:
    runs-on: ubuntu-latest
    steps:
      - uses: pdm-project/setup-pdm@v3
        name: Setup PDM
        with:
          python-version: 3.9
          architecture: x64
          version: 2.7.0
          cache: true
      - uses: actions/checkout@v3
      - name: Install dependencies
        run: pdm install
      - name: Test
        run: pdm test
