name: Create Staging Pull Requests
run-name: "Pull request by ${{ github.actor }}: ${{ github.event.pull_request.title }}"
on: workflow_dispatch
jobs:
  tests:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4
      - name: Create staging PR
        run: gh pr create --base staging --fill --title "staging push"
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
