name: Build and test
run-name: "Pull request by ${{ github.actor }}: ${{ github.event.pull_request.title }}"
on:
  pull_request:
    branches:
      - main
      - dev
  push:
    branches:
      - main
      - dev
env:
  HEAD_REF: ${{ github.head_ref }}
  REF_NAME: ${{ github.ref_name }}
  OR: ${{ github.head_ref || github.ref_name }}
  IMAGE_NAME: ${{ github.repository }}
jobs:
  tests:
    runs-on: ubuntu-latest
    steps:
      - name: Test
        run: echo ${{ env.HEAD_REF }}
      - name: Test2
        run: echo ${{ env.REF_NAME }}
      - name: Test3
        run: echo ${{ env.OR }}
